name: Validation
'on':
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch: null
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up NPM
        run: npm ci
      - name: Run Build
        run: npm run build
      - name: Run Tests
        run: npm test